export const CITIES = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Pune",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Chandigarh",
  "Kochi",
] as const;

export type City = (typeof CITIES)[number];

export const CITY_AREAS: Record<City, string[]> = {
  Mumbai: [
    "Andheri",
    "Bandra",
    "Borivali",
    "Dadar",
    "Juhu",
    "Kurla",
    "Malad",
    "Mulund",
    "Powai",
    "Thane",
    "Vashi",
    "Worli",
  ],
  Delhi: [
    "Connaught Place",
    "Dwarka",
    "Janakpuri",
    "Karol Bagh",
    "Lajpat Nagar",
    "Nehru Place",
    "Noida",
    "Pitampura",
    "Rohini",
    "Saket",
    "South Extension",
    "Vasant Kunj",
  ],
  Bangalore: [
    "Banashankari",
    "Electronic City",
    "HSR Layout",
    "Indiranagar",
    "Jayanagar",
    "JP Nagar",
    "Koramangala",
    "Malleshwaram",
    "Marathahalli",
    "Sarjapur",
    "Whitefield",
    "Yelahanka",
  ],
  Hyderabad: [
    "Ameerpet",
    "Banjara Hills",
    "Gachibowli",
    "Hitech City",
    "Jubilee Hills",
    "Kondapur",
    "Kukatpally",
    "LB Nagar",
    "Madhapur",
    "Manikonda",
    "Miyapur",
    "Secunderabad",
  ],
  Chennai: [
    "Adyar",
    "Anna Nagar",
    "Chromepet",
    "Guindy",
    "Mylapore",
    "Nungambakkam",
    "Perambur",
    "Porur",
    "Sholinganallur",
    "T Nagar",
    "Tambaram",
    "Velachery",
  ],
  Pune: [
    "Aundh",
    "Baner",
    "Deccan",
    "Hadapsar",
    "Hinjewadi",
    "Koregaon Park",
    "Kothrud",
    "Magarpatta",
    "Pimpri",
    "Shivajinagar",
    "Viman Nagar",
    "Wakad",
  ],
  Kolkata: [
    "Alipore",
    "Ballygunge",
    "Barrackpore",
    "Behala",
    "Dumdum",
    "Gariahat",
    "Howrah",
    "New Town",
    "Park Street",
    "Rajarhat",
    "Salt Lake",
    "Tollygunge",
  ],
  Ahmedabad: [
    "Bopal",
    "CG Road",
    "Chandkheda",
    "Gota",
    "Maninagar",
    "Naranpura",
    "Navrangpura",
    "Prahlad Nagar",
    "Satellite",
    "SG Highway",
    "Thaltej",
    "Vastrapur",
  ],
  Jaipur: [
    "Ajmer Road",
    "Bapu Nagar",
    "C-Scheme",
    "Durgapura",
    "Jagatpura",
    "Malviya Nagar",
    "Mansarovar",
    "Raja Park",
    "Sanganer",
    "Sodala",
    "Tonk Road",
    "Vaishali Nagar",
  ],
  Lucknow: [
    "Alambagh",
    "Aliganj",
    "Gomti Nagar",
    "Hazratganj",
    "Indira Nagar",
    "Jankipuram",
    "Kalyanpur",
    "Lucknow Cantonment",
    "Mahanagar",
    "Rajajipuram",
    "Sushant Golf City",
    "Vibhuti Khand",
  ],
  Chandigarh: [
    "Aerocity",
    "Industrial Area",
    "Manimajra",
    "Mohali",
    "Panchkula",
    "Sector 8",
    "Sector 15",
    "Sector 17",
    "Sector 22",
    "Sector 35",
    "Sector 43",
    "Zirakpur",
  ],
  Kochi: [
    "Aluva",
    "Edapally",
    "Fort Kochi",
    "Kakkanad",
    "Kaloor",
    "Marine Drive",
    "Palarivattom",
    "Panampilly Nagar",
    "Thrissur Road",
    "Tripunithura",
    "Vyttila",
    "Kottayam Road",
  ],
};
